source "https://rubygems.org"

# Specify your gem's dependencies in start_by_ruby.gemspec
#gemspec

gem "irb"
gem 'json'
gem "rake", "~> 13.0"
gem 'net-http-persistent', '~> 2.9'
gem 'pg'
gem 'sequel', '~> 4.36'
gem 'dotenv'